
phrases = [

'''Camarade, me dit-il, ni toi ni les tiens ne savez ce que c’est que chanter.'''
'''Vos airs sont fades et votre souffle écourté, comme vos idées et vos plaisirs.''',
'''Vous êtes une race de colimaçons, humant toujours même vent, et suçant même écorce ; car vous pensez que le monde finit à ces collines bleues qui cerclent votre ciel, et qui sont les forêts de mon pays.''',
'''Moi, je te dis, Tiennet, que c’est là que le monde commence, et que tu marcherais de ton meilleur pas, bien des jours et des nuits, avant de sortir de ces grands bois auprès desquels les vôtres sont des carrés de pois ramés.''',
'''Et quand tu en aurais gagné le bout, tu trouverais des montagnes, et encore des bois tels que tu n’en as jamais vus, car ce sont de grands et beaux sapins d’Auvergne inconnus dans vos plaines grasses.''',
'''Mais à quoi bon te parler de ces endroits que tu ne verras jamais ?''',
'''Le Berrichon, je le sais, est une pierre qui roule d’un sillon sur l’autre, revenant toujours sur celui de droite quand la charrue l’a poussé pour une saison sur celui de gauche.''',
'''Il respire un air lourd, il aime ses aises, il n’a point de curiosité ; il chérit son argent, et ne le dépense point ; mais il ne sait pas l’augmenter, et n’a ni invention ni courage.''',
'''Je ne dis pas ça pour toi, Tiennet ; tu sais te battre, mais c’est pour défendre ton bien, et tu ne saurais pas en acquérir par industrie, comme nous autres, esprits voyageurs, qui vivons partout comme chez nous, et prenons par ruse ou par force ce qu’on ne nous donne pas de bon gré.''',
'''Vous me parlez de conscience mal acquise mais, ami Tiennet, vous qui avez, je suppose, comme tous les petits propriétaires de ce pays, une vingtaine de moutons, deux ou trois chèvres, et peut-être une pauvre bourrique à nourrir sur le communal, quand, par inadvertance, vous les laissez peler les arbres et manger le blé vert du voisin, courez-vous en offrir réparation ?''',
'''Ne les ramenez-vous pas au plus vite sans rien dire, quand vous voyez paraître les gardes ?''',
'''Et s’ils vous font procédure, ne pestez-vous contre eux et contre la loi ?''',
'''Et si vous pouviez, sans danger, les tenir dans quelque bon coin, n’est-ce pas sur leurs épaules que vous payeriez l’amende à beaux coups de trique ?''',
'''Tenez ! c’est par couardise ou par force que vous respectez la règle, et c’est parce que nous y échappons que vous nous blâmez, par jalousie des franchises que nous savons prendre !''',
'''Je ne prétends point avoir dune meilleur musique, Tiennet ; mais je te dis que la chanson, la liberté, les beaux pays sauvages, la vivacité des esprits, et, si tu veux aussi, l’art de faire fortune sans devenir bête, tout ça se tient comme les doigts de la main.''',
'''Je te dis que crier n’est pas chanter, et que vous avez beau beugler comme des sourds dans vos champs et dans vos cabarets, ça ne fait pas de la musique.''',
''' La musique est chez nous, elle n’est pas chez vous. Ton ami Joset l’a bien senti, lui qui a les sens plus légers que toi ; car, pour toi, mon petit Tiennet, je vois bien que je perdrais mon temps à t’en vouloir montrer la différence.''',
'''Tu es un franc Berrichon, comme un moineau franc est un moineau franc, et ce que tu es à cette heure, tu le seras dans cinquante ans d’ici ; ton crin aura blanchi, mais ta cervelle n’aura pas pris un jour.''',
'''Je ne te juge pas sot.''',
'''Franc de ton cœur et fin de ton intérêt, tu l’es et le seras ; mais vivant de ton corps et léger de ton âme, tu ne saurais jamais l’être.''',
'''Voici pourquoi, Tiennet, regarde autour de nous les bons gros lits ventrus, où vous dormez dans la plume jusque par-dessus les yeux.''',
'''Vous êtes gens de bêche et de pioche, et faiseurs de grandes tâches qui se voient au soleil ; mais il vous faut ensuite la couette de fin duvet pour vous reposer.''',
'''Nous autres, gens des forêts, nous serions malades s’il fallait nous ensevelir vivants dans des draps et des couvertures.''',
'''Une hutte de branchage, un lit de fougère, voilà notre mobilier, et même ceux de nous qui voyagent sans cesse et qui ne se soucient pas de payer dans les auberges, ne supportent pas le toit d’une maison sur leurs têtes.''',
'''Au cœur des hivers, ils dorment à la franche étoile sur la bâtine de leurs mulets, et la neige leur sert de linge blanc.''',
'''Voilà des dressoirs, des tables, des chaises, de la belle vaisselle, des tasses de grès, du bon vin, une crémaillère, des pots à soupe, que sais-je ?''',
'''Il vous faut tout cela pour être contents ; vous mettez à chaque repas une bonne heure pour vous lester ; vous mâchonnez comme des bœufs qui ruminent ; aussi, quand il vous faut remettre sur vos jambes et retourner à l’ouvrage, vous avez un crève-cœur qui revient tous les jours deux ou trois fois.''',
'''Vous êtes lourds et pas plus gaillards d’esprit que vos bêtes de trait.''',
'''Le dimanche, accoudés sur des tables, mangeant plus que votre faim et buvant plus que votre soif, croyant vous divertir et vous réconforter en vous indigérant, soupirant pour des filles qui s’ennuient avec vous sans savoir pourquoi.''',
'''Dansant vos bourrées traînantes dans des chambres ou dans des granges où l’on étouffe, vous faites, d’un jour de liesse et de repos, une pesanteur de plus sur vos estomacs et sur vos esprits ; et la semaine entière vous en paraît plus triste, plus longue et plus dure.''',
'''Oui, Tiennet, voilà la vie que vous menez.''',
'''Pour trop chérir vos aises, vous vous faites trop de besoins, et pour trop bien vivre, vous ne vivez pas.''',
'''Tu me vois boire et causer, parce que j’aime le vin et que je suis un homme.''',
'''La table et la société me plaisent même beaucoup plus qu’à toi, par la raison que je n’en ai pas besoin et n’en fais pas mon habitude.''',
'''Toujours sur pied, mangeant sur le pouce, buvant aux fontaines que je rencontre, et dormant sous la feuillée du premier chêne venu, quand, par hasard, je trouve bonne table et bon vin à discrétion, c’est fête pour moi, ce n’est plus nécessité.''',
'''Vivant souvent seul des semaines entières, la société d’un ami m’est tout un dimanche, et dans une heure de causette, je lui en dis plus que dans une journée de cabaret.''',
'''Je jouis donc de tout, plus que vous autres, parce que je ne fais abus de rien.''',

]
